kind: Deployment
apiVersion: apps/v1
metadata:
  name: obscured-truth-ui
  namespace: obscured-truth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: obscured-truth-ui
  template:
    metadata:
      labels:
        app: obscured-truth-ui
    spec:
      containers:
      - name: obscure-truth-ui
        image: martinhodges/obscured-truth-ui:06
        ports:
        - containerPort: 80

